name: "Protocol Buffer Go Stubs Generation"
on:
  push:
    tags:
      - v**
jobs:
  generate-protoc:
    name: "Generate Proto"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: ["inventory"]
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.23
      - uses: actions/checkout@v2
      - name: Extract Release Version
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: "Generate for Golang"
        shell: bash
        run: |
          chmod +x "${GITHUB_WORKSPACE}/src/shared/protoc.sh"
          ls -alh ${GITHUB_WORKSPACE}
          cd ${GITHUB_WORKSPACE}/src/shared
          ./protoc.sh ${{ matrix.service }} ${{ env.RELEASE_VERSION }}
